-- Criação da tabela PESSOA
CREATE TABLE PESSOA
(
PESSOA_ID INT NOT NULL PRIMARY KEY,
NOME VARCHAR (200) NOT NULL, 
CPF VARCHAR (25) NOT NULL,
IDADE DATE, 
SEXO CHAR (1) NOT NULL
)

-- Criação da tabela ENDERECO
CREATE TABLE ENDERECO
(
ENDERECO_ID INT NOT NULL PRIMARY KEY,
TIPO  VARCHAR (10) NOT NULL,
LOGRADOURO VARCHAR (250) NOT NULL, 
NUMERO VARCHAR (10) NOT NULL, 
COMPLEMENTO   VARCHAR (100),
CEP NUMERIC NOT NULL, 
CIDADE VARCHAR (250) NOT NULL, 
ESTADO CHAR (2) NOT NULL, 
PESSOA_ID INT  NOT NULL,
	CONSTRAINT FK_PESSOA_ID 
	FOREIGN KEY (PESSOA_ID)
	REFERENCES PESSOA (PESSOA_ID)
)

-- Criação da consulta
SELECT	A.PESSOA_ID AS 'Id da Pessoa', 
		A.NOME as 'Nome', 
		A.CPF, 
		A.IDADE, 
		A.SEXO as 'Sexo', 
		B.TIPO as 'Tipo', 
		B.LOGRADOURO as 'Logradouro', 
		B.NUMERO as 'Numero', 
		B.COMPLEMENTO as 'Complemento', 
		B.CEP as 'Cep', 
		B.CIDADE as 'Cidade', 
		B.ESTADO as 'Estado'
FROM PESSOA A 
INNER JOIN ENDERECO B
ON A.PESSOA_ID = B.PESSOA_ID




